repositories:
  - name: stable
    url: https://charts.helm.sh/stable
  - name: jetstack
    url: https://charts.jetstack.io
  - name: harbor
    url: https://helm.goharbor.io

helmDefaults:
  createNamespace: true
  
releases:
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    needs:
      - nginx-ingress/nginx-ingress
    version: 1.1.0
    wait: true
    hooks:
      - events: ["prepare"]
        showlogs: true
        command: "kubectl"
        args: ["apply", "-f", "https://github.com/jetstack/cert-manager/releases/download/v1.1.0/cert-manager.crds.yaml"]
      - events: ["postsync"]
        showlogs: true
        command: "kubectl"
        args: ["apply", "-f", "../cert-manager/cluster-issuer.yaml"]

  - name: nginx-ingress
    namespace: nginx-ingress
    chart: stable/nginx-ingress
    version: 1.41.3
    wait: true

  - name: harbor
    namespace: harbor
    chart: harbor/harbor
    needs:
      - nginx-ingress/nginx-ingress
      - cert-manager/cert-manager
    version: 1.1.2
    wait: true
    values:
      - ../harbor/values.yaml